version: "3.8"

services:
    # PostgreSQL 数据库
    db:
        image: docker.io/postgres:17-alpine
        container_name: ov-blog-test-db
        restart: unless-stopped
        environment:
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        ports:
            - "5432:5432"
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres"]
            interval: 10s
            timeout: 5s
            retries: 5
            start_period: 30s
        volumes:
            - postgres_test_data:/var/lib/postgresql/data
        networks:
            - ov-blog-test-network

    # 应用服务
    app:
        build:
            context: .
            dockerfile: Dockerfile
            args:
                jobs: 4
        container_name: ov-blog-test-app
        restart: unless-stopped
        ports:
            - "3000:3000"
        env_file:
            - .env.test
        depends_on:
            db:
                condition: service_healthy
            interval: 30s
            timeout: 10s
            retries: 3
            start_period: 40s

        networks:
            - ov-blog-test-network

volumes:
    postgres_test_data:
        driver: local

networks:
    ov-blog-test-network:
        driver: bridge
