name: Docker Image Builder
run-name: ${{ github.actor }} - ${{ github.event_name }} - ${{ github.sha }}

# 在main分支上push时触发
on:
    push:
        branches:
            - main
            - dev
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2 # git pull      - name: Log in to Docker Hub
            - name: Docker meta
              id: meta
              uses: docker/metadata-action@v4
              with:
                  images: oveln/ov-blog
                  tags: |
                      type=raw,value=latest,enable={{is_default_branch}}
                      type=ref,event=tag
                      type=ref,event=branch
            - name: Login to Docker Hub
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Build Image
              uses: docker/build-push-action@v5
              with:
                  context: .
                  push: ${{ github.event_name != 'pull_request' }}
                  tags: ${{ steps.meta.outputs.tags }}
                  labels: ${{ steps.meta.outputs.labels }}
